### ISSUE TITLE
PWMOutput documentation

### ISSUE THREAD

**Issue by pbrais** [robo-crc/arduino-lib#6]
Bonjour, 

La documentation des paramètres du [InitializePwmOutput](https://github.com/robo-crc/arduino-lib/wiki/InitializePwmOutput) peut induire en erreur, surtout quand on n'a pas d'expérience avec les servo-moteurs.  Les arguments `minPeriod` et `maxPeriod` devraient plutôt être nommé: `minDuty` et `maxDuty`.  C'est le [duty cycle](https://en.wikipedia.org/wiki/Duty_cycle) que la méthode [SetPwmOutput](https://github.com/robo-crc/arduino-lib/wiki/SetPwmOutput) contrôle.  La période est le temps entre deux fronts montants consécutifs.

https://en.wikipedia.org/wiki/Pulse-width_modulation#Duty_cycle

**Comment by XavierStP** [comment]
Les arguments ne sont pas en Duty cycle.

Étant donné que les valeurs passées sont de 1000 ms à 2000 ms, cette donnée correspond à une période, qui par définition est un intervalle de temps.

Malgré que ces valeurs influencent le duty cycle, ces noms seraient erronnés.

Ces paramètres sont directement associés aux paramètres `min` et `max` de la méthode `Servo.Attach()`. Il serait peut-être plutot pertinent de les renommés `minPulsePeriod` et `maxPulsePeriod`

**Comment by pbrais** [comment]
Bonjour, 

Ok, effectivement le duty est exprimé en %.

Je ne mettrais pas `period` dans le nom de la variable. Le mot `period` ne veut pas nécessairement dire une période de temps, mais plutôt quelque chose qui est périodique et mesuré en temps.

J'opterais plus pour `minPulseWidth` et `maxPulseWidth` comme dans la description des paramètres de la documentation de `Servo.attach()`.

**Comment by sirrandalot** [comment]
Changed in v0.1.2
